Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.4"
  config.vm.network :forwarded_port, guest: 80, host: 9191
  config.vm.provision "file", source: "default.conf", destination: "default.conf"
  config.vm.provision "file", source: "info.php", destination: "info.php"
  config.vm.provision "file", source: "www.conf", destination: "www.conf"
  config.vm.provision "file", source: "php-fpm.conf", destination: "php-fpm.conf"
  config.vm.provision "shell", path: "provision.sh" 
end

puts "-------------------------------------------------"
puts "Default Homepage : http://localhost:9191"
puts "PHP Info         : http://localhost:9191/info.php"
puts "-------------------------------------------------"
