guest_ip  = "192.168.0.4"
host_port = "9494"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.4"
  config.vm.network "private_network", ip: guest_ip
  config.vm.network :forwarded_port, guest: 80, host: host_port
  config.vm.provision "file", source: "default.conf", destination: "default.conf"
  config.vm.provision "file", source: "info.php", destination: "info.php"
  config.vm.provision "file", source: "www.conf", destination: "www.conf"
  config.vm.provision "file", source: "php-fpm.conf", destination: "php-fpm.conf"
  config.vm.provision "shell", path: "provision.sh"
end

puts "-------------------------------------------------"
puts "Default Homepage : http://#{guest_ip}"
puts "PHP Info         : http://#{guest_ip}/info.php"
puts "-------------------------------------------------"
