guest_ip  = "192.168.0.3"
host_port = "9393"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "private_network", ip: guest_ip
  config.vm.network :forwarded_port, guest: 80, host: host_port
  config.vm.provision "file", source: "default.conf", destination: "default.conf"
  config.vm.provision "file", source: "list_nginx_files.sh", destination: "list_nginx_files.sh"
  config.vm.provision "shell", path: "provision.sh"
end

puts "-------------------------------------------------"
puts "Default Homepage : http://#{guest_ip}:#{host_port}"
puts "-------------------------------------------------"
